name: Train Model

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  train:
    name: Train (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: sudo apt-get install -y libsndfile1 wget unzip

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download and prepare data
      run: |
        mkdir -p training_data
        wget --no-check-certificate "https://drive.google.com/uc?export=download&id=1L0B8QAY5DmNs6G9rgzXGvpkQ0ZhGzCuU" -O dataset.zip
        unzip dataset.zip -d training_data/
        mv training_data/noises training_data/noise
        mkdir -p training_data/noise/cut
        mv training_data/noise/* training_data/noise/cut/ || true

    - name: Run training
      run: python train_model.py

    - name: Upload model
      uses: actions/upload-artifact@v4
      with:
        name: wooden-model-py${{ matrix.python-version }}
        path: wooden_hit_model.pkl